# Generated by Django 4.1 on 2022-09-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0003_alter_residence_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('FrontEnd', 'FrontEnd'), ('BackEnd', 'BackEnd'), ('FullStack', 'FullStack')], max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo')),
            ],
        ),
    ]
