# Generated by Django 4.1 on 2022-09-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeApp', '0004_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduation', models.CharField(max_length=50)),
                ('higher', models.CharField(max_length=50)),
                ('secondary', models.CharField(max_length=50)),
                ('degreemarks', models.FloatField()),
                ('highermarks', models.FloatField()),
                ('secondarymarks', models.FloatField()),
                ('degreedate', models.DateField()),
                ('higherdate', models.DateField()),
                ('secondarydate', models.DateField()),
            ],
        ),
    ]
